FIX resource 404's not returning error page
silverstripe/vendor-plugin pull request #45
Opened 2021-06-02 23:50 UTC by wilr

When viewing a resources URL which 404's (e.g https://www.silverstripe.com/_resources/themes/app/dist/images/404.jpg) the Apache default error page is shown rather than the SilverStripe provided 404 template.

2021-06-14 01:20 UTC, michalkleiner commented on resources/.htaccess
> +    <IfModule mod_dir.c>
Probably doesn't need to be nested within the rewrite module check, does it?

2021-09-10 00:46 UTC, michalkleiner requested changes

2021-09-10 00:46 UTC, michalkleiner commented on resources/.htaccess
> +    <IfModule mod_dir.c>
I'm happy to approve this if we move it outside of the rewrite module check @wilr

2021-09-10 00:49 UTC, wilr commented
@michalkleiner updated now

2021-09-10 01:56 UTC, michalkleiner commented
@emteknetnz I'm happy with this, we use it in PROD on CWP and it works ok. Do you see any issues with this change?

2021-09-10 01:57 UTC, michalkleiner approved these changes

2021-09-10 05:00 UTC, merged

2021-09-10 05:01 UTC, emteknetnz approved these changes